version: '3.1'

services:
    db:
        image: 'mysql:5.7.27'
        restart: always
        env_file:
            - ./wm_db.env
        environment:
            MYSQL_USER: wm_user
            MYSQL_DATABASE: wm_db
        ports:
            - 3306:3306
